apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
  namespace: healthcare
type: Opaque
stringData:
  JWT_SECRET: dev-secret-change-me
  JWT_EXPIRATION_MS: "86400000"
  STRIPE_SECRET_KEY: ""
  STRIPE_PUBLISHABLE_KEY: ""
  STRIPE_WEBHOOK_SECRET: ""
